spring.application.name=batch-processing-demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ankitjava?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Advika__18}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

server.port=8018

spring.batch.jdbc.initialize-schema=${SPRING_BATCH_JDBC_INITIALIZE_SCHEMA:always}
spring.batch.job.enabled=${SPRING_BATCH_JOB_ENABLED:false}